### ISSUE TITLE
Loading templates fail depending on network connection

### ISSUE THREAD

**Issue by tiandiyiqi** [Inventsable/bombino#4] opened 2020-06-03 06:32 UTC
⠙ Loading templates...[2020-06-03T06:30:16.660Z]  @firebase/firestore: Firestore (7.14.5): Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: FirebaseError: [code=unavailable]: 14 UNAVAILABLE: No connection established
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
(node:23431) UnhandledPromiseRejectionWarning: Error: 14 UNAVAILABLE: No connection established
    at Object.callErrorFromStatus (/usr/local/lib/node_modules/bombino/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/bombino/node_modules/@grpc/grpc-js/build/src/client.js:390:49)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/bombino/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
    at Http2CallStream.outputStatus (/usr/local/lib/node_modules/bombino/node_modules/@grpc/grpc-js/build/src/call-stream.js:114:27)
    at Http2CallStream.maybeOutputStatus (/usr/local/lib/node_modules/bombino/node_modules/@grpc/grpc-js/build/src/call-stream.js:153:22)
    at Http2CallStream.endCall (/usr/local/lib/node_modules/bombino/node_modules/@grpc/grpc-js/build/src/call-stream.js:140:18)
    at Http2CallStream.cancelWithStatus (/usr/local/lib/node_modules/bombino/node_modules/@grpc/grpc-js/build/src/call-stream.js:442:14)
    at ChannelImplementation.tryPick (/usr/local/lib/node_modules/bombino/node_modules/@grpc/grpc-js/build/src/channel.js:223:32)
    at ChannelImplementation._startCallStream (/usr/local/lib/node_modules/bombino/node_modules/@grpc/grpc-js/build/src/channel.js:253:14)
    at Http2CallStream.start (/usr/local/lib/node_modules/bombino/node_modules/@grpc/grpc-js/build/src/call-stream.js:419:22)
(node:23431) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23431) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Inventsable** [comment] 2020-06-03 22:21
Hmmm, I'd never seen this before. Do you mind posting the results of an internet speed test here?

> 14 UNAVAILABLE: No connection established
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.

It looks like this is due to internet speed not being fast enough to access the backend. I chose to have bombino templates backed with Firebase so that users wouldn't have to redownload it to update to new templates, but I could add a third option like "Static" that would pull templates from a JSON -- this isn't ideal because the templates aren't attached to bombino in any tangible way and can cause it to fail if their repos are renamed, moved or deleted. 

Don't see much a choice here, though. I'll try to update this really soon and tag you here.

**Comment by tiandiyiqi** [comment] 2020-06-07 00:06
Thank U very much

**Comment by Inventsable** [comment] 2020-06-13 05:59
Sorry for the delay, just started a new job and have been extremely busy this week.

Try `npm install bombino@1.3.0`. I've added a new template type via 822db5b1d7d72d8ffec324afd835d9a97e045118 that's completely static and will solve the initial Firebase issue -- but just as a warning, if your internet connection times out for Firebase there's a chance it may also timeout for the download of the github template as well. I'll need to you verify this isn't the case because I'm not able to reproduce it.

I'm going to close this issue unless I hear back about further problems. Thanks!

**Closed by Inventsable** 2020-06-13 05:59 UTC
Labels: bug
